const canvas=document.getElementById('game');
const ctx=canvas.getContext('2d');
const radar=document.getElementById('radar');
const rctx=radar.getContext('2d');
const cashEl=document.getElementById('cash');
const progressEl=document.getElementById('progress');
const start=document.getElementById('start');
const startBtn=document.getElementById('startBtn');
const dashBtn=document.getElementById('dashBtn');
const actBtn=document.getElementById('actBtn');
const stick=document.querySelector('.stick');
const keys=new Set();
const pointer={down:false,tx:0,ty:0,joy:false,jx:0,jy:0};
const game={running:false,t:0,cash:12540,kills:0,shake:0,cool:0,player:{x:0,y:0,dash:0,hp:100},rivals:[],drops:[],cars:[],shots:[],fx:[],rain:[]};
function resize(){canvas.width=innerWidth;canvas.height=innerHeight;if(!game.player.x){game.player.x=innerWidth/2;game.player.y=innerHeight/2}}resize();addEventListener('resize',resize);
function rnd(a,b){return a+Math.random()*(b-a)}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function money(n){return '$'+Math.floor(n).toLocaleString()}
function reset(){game.running=true;game.t=0;game.cash=12540;game.kills=0;game.player.x=innerWidth/2;game.player.y=innerHeight/2;game.rivals=[];game.drops=[];game.cars=[];game.shots=[];game.fx=[];game.rain=[];for(let i=0;i<15;i++)spawnRival();for(let i=0;i<28;i++)spawnDrop();for(let i=0;i<14;i++)game.cars.push({x:rnd(220,innerWidth-220),y:rnd(120,innerHeight-120),v:rnd(25,80),c:i%2?'#ff2d74':'#00d8ff'});for(let i=0;i<160;i++)game.rain.push({x:rnd(0,innerWidth),y:rnd(0,innerHeight),v:rnd(300,700)});cashEl.textContent=money(game.cash);progressEl.textContent=game.kills;if(start)start.style.display='none'}
function spawnRival(){game.rivals.push({x:rnd(160,innerWidth-160),y:rnd(120,innerHeight-120),hp:40,a:rnd(0,6.28)})}
function spawnDrop(){game.drops.push({x:rnd(160,innerWidth-160),y:rnd(120,innerHeight-120),v:50})}
function burst(x,y,color,n=10){for(let i=0;i<n;i++)game.fx.push({x,y,vx:rnd(-180,180),vy:rnd(-180,180),life:rnd(.25,.7),c:color})}
function nearest(){let best=null,d=99999;for(const e of game.rivals){const n=Math.hypot(e.x-game.player.x,e.y-game.player.y);if(n<d){d=n;best=e}}return best}
function pulse(){if(!game.running)return;const e=nearest();if(!e)return;game.shots.push({x:game.player.x,y:game.player.y,tx:e.x,ty:e.y,life:.12});e.hp-=24;burst(e.x,e.y,'#ffd35a',4);if(e.hp<=0){game.kills++;game.cash+=180;progressEl.textContent=game.kills;cashEl.textContent=money(game.cash);burst(e.x,e.y,'#ff2d74',18);game.rivals=game.rivals.filter(x=>x!==e);spawnRival();spawnDrop();game.shake=10}}
function dash(){if(game.running){game.player.dash=.18;game.shake=4}}
canvas.addEventListener('pointerdown',e=>{pointer.down=true;pointer.tx=e.clientX;pointer.ty=e.clientY});canvas.addEventListener('pointermove',e=>{if(pointer.down){pointer.tx=e.clientX;pointer.ty=e.clientY}});addEventListener('pointerup',()=>{pointer.down=false;pointer.joy=false;pointer.jx=0;pointer.jy=0});if(stick){stick.addEventListener('pointerdown',e=>{pointer.joy=true;stick.setPointerCapture(e.pointerId);setJoy(e)});stick.addEventListener('pointermove',e=>{if(pointer.joy)setJoy(e)});stick.addEventListener('pointerup',()=>{pointer.joy=false;pointer.jx=0;pointer.jy=0})}function setJoy(e){const r=stick.getBoundingClientRect();const cx=r.left+r.width/2,cy=r.top+r.height/2;pointer.jx=clamp((e.clientX-cx)/(r.width*.34),-1,1);pointer.jy=clamp((e.clientY-cy)/(r.height*.34),-1,1)}
startBtn.onclick=reset;dashBtn.onclick=dash;actBtn.onclick=pulse;addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.code==='Space')pulse();if(e.key==='Shift')dash()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function input(){let x=0,y=0;if(keys.has('a')||keys.has('arrowleft'))x--;if(keys.has('d')||keys.has('arrowright'))x++;if(keys.has('w')||keys.has('arrowup'))y--;if(keys.has('s')||keys.has('arrowdown'))y++;if(pointer.joy){x+=pointer.jx;y+=pointer.jy}else if(pointer.down){const dx=pointer.tx-game.player.x,dy=pointer.ty-game.player.y,d=Math.hypot(dx,dy);if(d>12){x+=dx/d;y+=dy/d}}const l=Math.hypot(x,y)||1;return{x:x/l,y:y/l}}
function update(dt){game.t+=dt;if(!game.running)return;const a=input();const sp=game.player.dash>0?620:260;game.player.dash=Math.max(0,game.player.dash-dt);game.player.x=clamp(game.player.x+a.x*sp*dt,70,innerWidth-70);game.player.y=clamp(game.player.y+a.y*sp*dt,90,innerHeight-70);game.cool-=dt;if(game.cool<=0){game.cool=.55;pulse()}for(const e of game.rivals){const dx=game.player.x-e.x,dy=game.player.y-e.y,l=Math.hypot(dx,dy)||1;e.x+=dx/l*55*dt;e.y+=dy/l*55*dt;e.a+=dt*4;if(l<34){game.player.hp=Math.max(0,game.player.hp-10*dt);game.shake=5}}for(const d of [...game.drops]){if(Math.hypot(d.x-game.player.x,d.y-game.player.y)<42){game.cash+=d.v;cashEl.textContent=money(game.cash);burst(d.x,d.y,'#42ef74',8);game.drops=game.drops.filter(x=>x!==d);spawnDrop()}}for(const c of game.cars){c.y+=c.v*dt;if(c.y>innerHeight+80)c.y=-80}for(const f of game.fx){f.x+=f.vx*dt;f.y+=f.vy*dt;f.life-=dt}game.fx=game.fx.filter(f=>f.life>0);for(const s of game.shots)s.life-=dt;game.shots=game.shots.filter(s=>s.life>0);for(const r of game.rain){r.y+=r.v*dt;r.x-=r.v*.18*dt;if(r.y>innerHeight){r.y=-20;r.x=rnd(0,innerWidth)}}game.shake*=.86}
function drawCity(){const g=ctx.createLinearGradient(0,0,innerWidth,innerHeight);g.addColorStop(0,'#071023');g.addColorStop(.5,'#05070d');g.addColorStop(1,'#02030a');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight);ctx.save();ctx.translate(innerWidth*.15,innerHeight*.15);ctx.rotate(-.45);for(let y=-600;y<innerHeight+700;y+=140){for(let x=-700;x<innerWidth+800;x+=190){const neon=(x+y)%2?'#ff2d74':'#00d8ff';ctx.fillStyle='#08101d';ctx.fillRect(x,y,130,90);ctx.strokeStyle=neon;ctx.lineWidth=3;ctx.shadowColor=neon;ctx.shadowBlur=10;ctx.strokeRect(x,y,130,90);ctx.shadowBlur=0;ctx.fillStyle=neon;for(let i=0;i<24;i++){if((i+x+y)%3)ctx.fillRect(x+12+(i%6)*18,y+12+Math.floor(i/6)*18,8,9)}}}ctx.restore();ctx.strokeStyle='rgba(255,255,255,.16)';ctx.lineWidth=28;ctx.beginPath();ctx.moveTo(innerWidth*.2,innerHeight+80);ctx.lineTo(innerWidth*.78,-80);ctx.moveTo(-80,innerHeight*.7);ctx.lineTo(innerWidth+80,innerHeight*.35);ctx.stroke()}
function draw(){ctx.save();if(game.shake)ctx.translate(rnd(-game.shake,game.shake),rnd(-game.shake,game.shake));drawCity();for(const c of game.cars){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(-.45);ctx.shadowColor=c.c;ctx.shadowBlur=18;ctx.fillStyle='#131a29';ctx.fillRect(-28,-48,56,96);ctx.fillStyle=c.c;ctx.fillRect(-22,-42,44,10);ctx.restore()}for(const d of game.drops){ctx.shadowColor='#42ef74';ctx.shadowBlur=18;ctx.fillStyle='#42ef74';ctx.fillRect(d.x-18,d.y-11,36,22);ctx.shadowBlur=0}for(const e of game.rivals){ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.a);ctx.shadowColor='#ff2d74';ctx.shadowBlur=20;ctx.fillStyle='#121827';ctx.beginPath();ctx.arc(0,0,20,0,7);ctx.fill();ctx.strokeStyle='#ff2d74';ctx.lineWidth=4;ctx.strokeRect(-15,-15,30,30);ctx.fillStyle='#ffd35a';ctx.fillRect(-18,-30,36*(e.hp/40),5);ctx.restore()}ctx.save();ctx.translate(game.player.x,game.player.y);ctx.shadowColor='#46d9ff';ctx.shadowBlur=25;ctx.strokeStyle='#46d9ff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,34+Math.sin(game.t*6)*3,0,7);ctx.stroke();ctx.fillStyle='#ffd35a';ctx.beginPath();ctx.arc(0,0,18,0,7);ctx.fill();ctx.restore();ctx.strokeStyle='#ffd35a';ctx.lineWidth=4;for(const s of game.shots){ctx.globalAlpha=Math.max(0,s.life/.12);ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.tx,s.ty);ctx.stroke();ctx.globalAlpha=1}for(const f of game.fx){ctx.globalAlpha=Math.max(0,f.life);ctx.fillStyle=f.c;ctx.beginPath();ctx.arc(f.x,f.y,4+f.life*6,0,7);ctx.fill();ctx.globalAlpha=1}ctx.strokeStyle='rgba(125,220,255,.25)';ctx.lineWidth=1;for(const r of game.rain){ctx.beginPath();ctx.moveTo(r.x,r.y);ctx.lineTo(r.x-8,r.y+20);ctx.stroke()}ctx.restore();drawRadar()}
function drawRadar(){rctx.clearRect(0,0,radar.width,radar.height);rctx.fillStyle='rgba(4,10,22,.9)';rctx.fillRect(0,0,radar.width,radar.height);rctx.strokeStyle='rgba(120,210,255,.15)';for(let x=0;x<radar.width;x+=28){rctx.beginPath();rctx.moveTo(x,0);rctx.lineTo(x,radar.height);rctx.stroke()}for(let y=0;y<radar.height;y+=28){rctx.beginPath();rctx.moveTo(0,y);rctx.lineTo(radar.width,y);rctx.stroke()}const sx=radar.width/innerWidth,sy=radar.height/innerHeight;rctx.fillStyle='#ffd35a';rctx.beginPath();rctx.arc(game.player.x*sx,game.player.y*sy,5,0,7);rctx.fill();rctx.fillStyle='#ff2d74';for(const e of game.rivals){rctx.beginPath();rctx.arc(e.x*sx,e.y*sy,3,0,7);rctx.fill()}}
let last=0;function loop(t){const dt=Math.min(.033,(t-last||16)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);setTimeout(reset,120);
