(() => {
  const S = {
    active:false, started:false, t:0, cash:12540, gold:125, energy:12, health:100, heat:7,
    player:{x:600,y:420,vx:0,vy:0,fire:0,dash:0}, enemies:[], cashDrops:[], shots:[], fx:[], keys:new Set(), firing:false
  };
  const $ = (id)=>document.getElementById(id);
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const money=(n)=>'$'+Math.floor(n).toLocaleString();

  function boot(){
    if($('cinematicMode')) return;
    const css=document.createElement('link'); css.rel='stylesheet'; css.href='cinematic.css?v=6'; document.head.appendChild(css);
    const open=document.createElement('button'); open.className='cinematic-open'; open.textContent='▶ Cinematic City'; document.body.appendChild(open);
    const root=document.createElement('section'); root.id='cinematicMode'; root.className='cinematic-mode'; root.style.display='none';
    root.innerHTML=`<canvas id="cinCanvas" class="cinematic-canvas"></canvas><div class="cinematic-hud"><button id="cinClose" class="cinematic-close">×</button><div class="hud-top"><div class="profile-card"><div class="avatar"></div><div><h2>Rookie ✎</h2><div class="level">LVL 7 <span style="float:right">320 / 900 XP</span></div><div class="xpbar"><span></span></div></div></div><div class="hud-pill">💵 <b id="cinCash">$12,540</b><span class="plus">+</span></div><div class="hud-pill">🟨 <b id="cinGold">125</b><span class="plus">+</span></div><div class="hud-pill">⚡ <b id="cinEnergy">12/12</b><span class="plus">+</span></div><div class="top-buttons"><button class="top-btn"><b>🏆</b>Rank</button><button class="top-btn"><b>📋</b>Mission</button><button class="top-btn"><b>🛒</b>Store</button><button class="top-btn"><b>⚙</b>Settings</button></div></div><div class="event-banner"><b>DOUBLE CASH EVENT 2X</b></div><div class="mission-panel"><h3>💀 MAIN MISSION</h3><h2>TAKE OVER THE BLOCK</h2><p>Eliminate <span id="cinKills">0</span>/25 enemies and secure cash.</p><div class="reward">REWARD: $2,500</div></div><div class="side-panel"><button><span>▦</span>CITY</button><button><span>▣</span>ARSENAL</button><button><span>♛</span>EMPIRE</button><button><span>◆</span>UPGRADES</button></div><div class="wanted-panel"><div class="heat-title"><b>HEAT LEVEL</b><span>7/10</span></div><div class="heat-bars"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div><div class="stars">★★★★★</div></div><div class="mini-map"><div class="mini-player"></div><i class="mini-dot" style="left:22%;top:55%"></i><i class="mini-dot" style="left:63%;top:42%"></i><i class="mini-dot" style="left:72%;top:70%"></i></div><div class="joystick"></div><div class="action-pad"><button id="grenadeBtn" class="grenade-btn">💣<br>3</button><button id="skillBtn" class="skill-btn">👟</button><button id="dashBtn" class="sprint-btn">DASH</button><button id="fireBtn" class="fire-btn">⌖</button></div><div class="upgrade-row"><div class="upgrade-card"><h4>HEALTH</h4><div class="icon">💗</div><small>LVL 3</small><div class="bar"><span style="width:60%"></span></div></div><div class="upgrade-card"><h4>DAMAGE</h4><div class="icon">🗡</div><small>LVL 2</small><div class="bar"><span style="width:44%"></span></div></div><div class="upgrade-card"><h4>ARMOR</h4><div class="icon">🛡</div><small>LVL 2</small><div class="bar"><span style="width:52%"></span></div></div><div class="upgrade-card"><h4>CASH INCOME</h4><div class="icon">💲</div><small>LVL 4</small><div class="bar"><span style="width:74%"></span></div></div></div><div class="chat-bar">💬 [GLOBAL] KingViper: Just took over Downtown!<br>[CREW] Shadow: Let’s raid their block tonight.</div><button id="cinPlay" class="play-splash"><div>PLAY<small>ENTER THE CITY</small></div></button></div>`;
    document.body.appendChild(root);
    open.onclick=()=>{root.style.display='block';S.active=true;resize();}; $('cinClose').onclick=()=>{root.style.display='none';S.active=false;}; $('cinPlay').onclick=()=>start(); $('fireBtn').onpointerdown=()=>S.firing=true; $('fireBtn').onpointerup=()=>S.firing=false; $('dashBtn').onclick=()=>S.player.dash=.18;
    addEventListener('keydown',e=>{S.keys.add(e.key.toLowerCase()); if(e.code==='Space')S.firing=true; if(e.key==='Shift')S.player.dash=.18;}); addEventListener('keyup',e=>{S.keys.delete(e.key.toLowerCase()); if(e.code==='Space')S.firing=false;});
    resize(); requestAnimationFrame(loop);
  }
  function resize(){const c=$('cinCanvas'); if(!c)return; c.width=innerWidth; c.height=innerHeight;}
  addEventListener('resize',resize);
  function start(){S.started=true; $('cinPlay').style.display='none'; S.player.x=innerWidth*.48; S.player.y=innerHeight*.58; S.enemies=[]; S.cashDrops=[]; for(let i=0;i<12;i++)spawnEnemy(); for(let i=0;i<24;i++)spawnCash();}
  function spawnEnemy(){S.enemies.push({x:80+Math.random()*(innerWidth-160),y:120+Math.random()*(innerHeight-220),hp:45});}
  function spawnCash(){S.cashDrops.push({x:80+Math.random()*(innerWidth-160),y:120+Math.random()*(innerHeight-220)});}
  function axis(){let x=0,y=0;if(S.keys.has('a')||S.keys.has('arrowleft'))x--;if(S.keys.has('d')||S.keys.has('arrowright'))x++;if(S.keys.has('w')||S.keys.has('arrowup'))y--;if(S.keys.has('s')||S.keys.has('arrowdown'))y++;let l=Math.hypot(x,y)||1;return{x:x/l,y:y/l};}
  function nearest(){let b=null,d=1e9;for(const e of S.enemies){let n=Math.hypot(e.x-S.player.x,e.y-S.player.y);if(n<d){d=n;b=e;}}return b;}
  function fire(){const e=nearest();if(!e)return;S.shots.push({x:S.player.x,y:S.player.y,tx:e.x,ty:e.y,life:.13});e.hp-=25;if(e.hp<=0){S.cash+=150;S.enemies=S.enemies.filter(x=>x!==e);spawnEnemy();spawnCash();$('cinCash').textContent=money(S.cash);$('cinKills').textContent=Number($('cinKills').textContent||0)+1;}}
  function update(dt){if(!S.started)return;S.t+=dt;const a=axis(),speed=S.player.dash>0?620:270;S.player.dash=Math.max(0,S.player.dash-dt);S.player.x=clamp(S.player.x+a.x*speed*dt,50,innerWidth-50);S.player.y=clamp(S.player.y+a.y*speed*dt,90,innerHeight-60);S.player.fire-=dt;if(S.firing&&S.player.fire<=0){S.player.fire=.16;fire();}for(const e of S.enemies){let dx=S.player.x-e.x,dy=S.player.y-e.y,l=Math.hypot(dx,dy)||1;e.x+=dx/l*45*dt;e.y+=dy/l*45*dt;}for(const c of [...S.cashDrops]){if(Math.hypot(c.x-S.player.x,c.y-S.player.y)<42){S.cash+=50;S.cashDrops=S.cashDrops.filter(x=>x!==c);spawnCash();$('cinCash').textContent=money(S.cash);}}S.shots.forEach(s=>s.life-=dt);S.shots=S.shots.filter(s=>s.life>0);}
  function city(ctx,w,h){ctx.fillStyle='#05070d';ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(w*.08,h*.12);ctx.rotate(-.32);for(let y=-500;y<h+600;y+=135){for(let x=-700;x<w+800;x+=180){let neon=(x+y)%2?'#ff2d74':'#00d8ff';ctx.fillStyle='#07101e';ctx.fillRect(x,y,130,94);ctx.strokeStyle=neon;ctx.lineWidth=3;ctx.strokeRect(x,y,130,94);ctx.fillStyle=neon;for(let i=0;i<24;i++)if((i+x+y)%3)ctx.fillRect(x+12+(i%6)*18,y+12+Math.floor(i/6)*18,8,9);}}ctx.restore();ctx.strokeStyle='rgba(255,255,255,.15)';ctx.lineWidth=24;ctx.beginPath();ctx.moveTo(w*.16,h);ctx.lineTo(w*.72,0);ctx.moveTo(0,h*.68);ctx.lineTo(w,h*.34);ctx.stroke();}
  function draw(){const c=$('cinCanvas');if(!c)return;const ctx=c.getContext('2d'),w=c.width,h=c.height;city(ctx,w,h);for(const cash of S.cashDrops){ctx.shadowBlur=18;ctx.shadowColor='#42ef74';ctx.fillStyle='#42ef74';ctx.fillRect(cash.x-16,cash.y-10,32,20);ctx.shadowBlur=0;}for(const e of S.enemies){ctx.shadowBlur=18;ctx.shadowColor='#ff2d74';ctx.fillStyle='#111827';ctx.beginPath();ctx.arc(e.x,e.y,18,0,7);ctx.fill();ctx.fillStyle='#ff2d74';ctx.fillRect(e.x-18,e.y-30,36,5);ctx.fillStyle='#ffd35a';ctx.fillRect(e.x-18,e.y-30,36*(e.hp/45),5);ctx.shadowBlur=0;}ctx.shadowBlur=26;ctx.shadowColor='#46d9ff';ctx.strokeStyle='#46d9ff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(S.player.x,S.player.y,34+Math.sin(S.t*5)*3,0,7);ctx.stroke();ctx.fillStyle='#ffd35a';ctx.beginPath();ctx.arc(S.player.x,S.player.y,18,0,7);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#ffd35a';ctx.lineWidth=4;for(const s of S.shots){ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.tx,s.ty);ctx.stroke();}}
  let last=0;function loop(t){let dt=Math.min(.033,(t-last||16)/1000);last=t;if(S.active){update(dt);draw();}requestAnimationFrame(loop);} document.addEventListener('DOMContentLoaded',boot);
})();